# Generated by Django 4.2.13 on 2024-07-02 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_valid_until', models.DateField()),
                ('article_name', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyFormHeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('organization', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyFormLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distribution_value', models.IntegerField()),
                ('target_distribution_value', models.IntegerField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('form_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.monthlyformheader')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicator')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthlyformline_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
