# Generated by Django 4.2.13 on 2024-07-09 10:50

from django.db import migrations, connection

def create_view(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            CREATE OR REPLACE VIEW full_report AS
SELECT 
    c.name AS company_name,
    h.start_date,
    h.end_date,
    h.created_at AS header_created_at,
    i.article_name,
    i.order AS article_order,
    l.distribution_value,
    l.target_distribution_value
FROM 
    indicators_company c 
JOIN 
    indicators_monthlyformheader h ON c.id = h.organization_id
JOIN 
    indicators_monthlyformline l ON h.id = l.form_header_id
JOIN 
    indicators_indicator i ON l.indicator_id = i.id;
        """)

def drop_view(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("DROP VIEW IF EXISTS full_report")

class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_company_users'),
    ]

    operations = [
        migrations.RunPython(create_view, reverse_code=drop_view),
    ]
